### ISSUE TITLE
跨校区报备未能实现选择可出入校区

### ISSUE THREAD

**Issue by lutarioriparia** [iBug/thu-checkin#7]
3.21更新后说明文档里增添了RETURN_COLLEGE，但代码里并没有涉及这一项，报备结果的“可出入校区”一栏是空白的。
请问是目前还无法做到自动填写这一项信息，还是更新的代码有遗漏？

**Comment by iBug** [comment]
是我傻了，代码忘记改了

因为我自用的版本和仓库里的版本有较大出入，所以两个版本是分开维护的，每次把自用版 debug 好之后再手工同步修改的，所以有时候会忘东西
